services:
  laowang-sub-converter:
#    build: .
    image: qq510023514/sub-converter:latest
    container_name: laowang-sub-converter
    environment:
      NODE_ENV: production
      PORT: 3000
      DATA_DIR: /app/data
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./custom_templates.json:/app/custom_templates.json:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true