import yaml from 'js-yaml'
import { applyRulePreset } from './rules.js'
import { base64 } from './parsers.js'
import { BASE64_TARGETS, SING_BOX_TARGETS, YAML_TARGETS, normalizeTarget } from './targets.js'

export function convertToTarget(nodes, target, options = {}) {
    const normalized = normalizeTarget(target)
    const safeOptions = {
        udp: options.udp !== false,
        skipCert: options.skipCert === true,
        rulePreset: options.rulePreset || ''
    }

    if (YAML_TARGETS.has(normalized)) return convertToClash(nodes, safeOptions, normalized)
    if (normalized === 'surge' || normalized === 'surfboard') return convertToSurge(nodes, safeOptions)
    if (normalized === 'quantumultx') return convertToQuantumultX(nodes, safeOptions)
    if (normalized === 'loon') return convertToLoon(nodes, safeOptions)
    if (BASE64_TARGETS.has(normalized)) return convertToBase64(nodes)
    if (SING_BOX_TARGETS.has(normalized)) return convertToSingBox(nodes, safeOptions)
    return ''
}

function convertToClash(nodes, options, target) {
    const proxies = nodes.map(node => toClashProxy(node, options, target)).filter(Boolean)
    const names = proxies.map(proxy => proxy.name)
    const { proxyGroups, rules } = options.rulePreset
        ? applyRulePreset(names, options.rulePreset)
        : applyRulePreset(names, 'basic')

    return [
        '# Generated by LaoWang Sub Converter',
        `# Nodes: ${proxies.length}`,
        `# Target: ${target}`,
        `# Generated: ${new Date().toISOString()}`,
        '',
        yaml.dump({
            proxies,
            'proxy-groups': proxyGroups,
            rules
        }, {
            lineWidth: -1,
            noRefs: true,
            sortKeys: false
        })
    ].join('\n')
}

function toClashProxy(node, options, target) {
    const extended = target !== 'clash'
    const base = {
        name: node.name,
        server: node.server,
        port: node.port,
        udp: options.udp
    }

    switch (node.type) {
        case 'ss':
            return { ...base, type: 'ss', cipher: node.method, password: node.password }
        case 'ssr':
            return {
                ...base,
                type: 'ssr',
                cipher: node.method,
                password: node.password,
                protocol: node.protocol,
                'protocol-param': node.protocolParam || '',
                obfs: node.obfs,
                'obfs-param': node.obfsParam || ''
            }
        case 'vmess':
            return withTransport({
                ...base,
                type: 'vmess',
                uuid: node.uuid,
                alterId: node.alterId || 0,
                cipher: node.cipher || 'auto',
                tls: node.tls || undefined,
                servername: node.tls ? node.sni : undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined,
                network: node.network !== 'tcp' ? node.network : undefined
            }, node)
        case 'vless':
            if (!extended) return null
            return withTransport({
                ...base,
                type: 'vless',
                uuid: node.uuid,
                flow: node.flow || undefined,
                tls: node.tls || undefined,
                servername: node.sni || undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined,
                network: node.network !== 'tcp' ? node.network : undefined,
                'reality-opts': node.reality ? {
                    'public-key': node.reality.publicKey,
                    'short-id': node.reality.shortId || undefined
                } : undefined,
                'client-fingerprint': node.reality?.fingerprint || undefined
            }, node)
        case 'trojan':
            return withTransport({
                ...base,
                type: 'trojan',
                password: node.password,
                sni: node.sni || undefined,
                alpn: node.alpn?.length ? node.alpn : undefined,
                'skip-cert-verify': options.skipCert
            }, node)
        case 'hysteria':
            if (!extended) return null
            return {
                ...base,
                type: 'hysteria',
                auth_str: node.auth,
                up: node.up,
                down: node.down,
                alpn: [node.alpn || 'h3'],
                obfs: node.obfs || undefined,
                sni: node.sni || undefined,
                'skip-cert-verify': node.insecure || options.skipCert
            }
        case 'hysteria2':
            if (!extended) return null
            return {
                ...base,
                type: 'hysteria2',
                password: node.password,
                sni: node.sni || undefined,
                obfs: node.obfs || undefined,
                'obfs-password': node.obfs ? node.obfsPassword || '' : undefined,
                'skip-cert-verify': node.insecure || options.skipCert
            }
        case 'tuic':
            if (!extended) return null
            return {
                ...base,
                type: 'tuic',
                uuid: node.uuid,
                password: node.password,
                alpn: node.alpn || ['h3'],
                'congestion-controller': node.congestion || 'bbr',
                sni: node.sni || undefined,
                'skip-cert-verify': node.insecure || options.skipCert,
                'udp-relay-mode': node.udpRelayMode || 'native',
                'reduce-rtt': true
            }
        case 'anytls':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'anytls',
                password: node.password,
                sni: node.sni || undefined,
                alpn: node.alpn?.length ? node.alpn : undefined,
                'skip-cert-verify': node.insecure || options.skipCert,
                'client-fingerprint': node.fingerprint || undefined,
                'idle-session-check-interval': node.idleSessionCheckInterval || undefined,
                'idle-session-timeout': node.idleSessionTimeout || undefined,
                'min-idle-session': node.minIdleSession ?? undefined
            })
        case 'snell':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'snell',
                psk: node.psk,
                version: node.version || 3,
                obfs: node.obfs || undefined,
                'obfs-opts': node.obfs ? { mode: node.obfs, host: node.obfsHost || undefined } : undefined
            })
        case 'http':
            return dropUndefined({
                ...base,
                type: 'http',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls || undefined,
                sni: node.sni || undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined
            })
        case 'socks5':
            return dropUndefined({
                ...base,
                type: 'socks5',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls || undefined
            })
        default:
            return null
    }
}

function withTransport(proxy, node) {
    if (node.network === 'ws' && node.ws) {
        proxy.network = 'ws'
        proxy['ws-opts'] = {
            path: node.ws.path || '/',
            headers: node.ws.headers || {}
        }
    }
    if (node.network === 'grpc' && node.grpc) {
        proxy.network = 'grpc'
        proxy['grpc-opts'] = {
            'grpc-service-name': node.grpc.serviceName || ''
        }
    }
    return dropUndefined(proxy)
}

function convertToSurge(nodes, options) {
    const proxies = nodes
        .map(node => ({ node, line: toSurgeLine(node, options) }))
        .filter(item => item.line)
    const lines = ['[Proxy]']
    for (const proxy of proxies) lines.push(proxy.line)
    if (!proxies.length) return ''

    lines.push('', '[Proxy Group]', `PROXY = select, ${proxies.map(item => item.node.name).join(', ')}`)
    lines.push('', '[Rule]', 'GEOIP,CN,DIRECT', 'FINAL,PROXY')
    return lines.join('\n')
}

function toSurgeLine(node, options) {
    switch (node.type) {
        case 'ss':
            return `${node.name} = ss, ${node.server}, ${node.port}, encrypt-method=${node.method}, password=${node.password}, udp-relay=${options.udp}`
        case 'vmess':
            return appendParts(`${node.name} = vmess, ${node.server}, ${node.port}, username=${node.uuid}`, [
                'vmess-aead=true',
                node.tls && 'tls=true',
                node.sni && `sni=${node.sni}`,
                node.ws && 'ws=true',
                node.ws?.path && `ws-path=${node.ws.path}`,
                node.ws?.headers?.Host && `ws-headers=Host:${node.ws.headers.Host}`,
                options.skipCert && 'skip-cert-verify=true'
            ])
        case 'trojan':
            return appendParts(`${node.name} = trojan, ${node.server}, ${node.port}, password=${node.password}`, [
                node.sni && `sni=${node.sni}`,
                options.skipCert && 'skip-cert-verify=true'
            ])
        case 'hysteria2':
            return appendParts(`${node.name} = hysteria2, ${node.server}, ${node.port}, password=${node.password}`, [
                node.sni && `sni=${node.sni}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'snell':
            return appendParts(`${node.name} = snell, ${node.server}, ${node.port}, psk=${node.psk}, version=${node.version || 3}`, [
                node.obfs && `obfs=${node.obfs}`,
                node.obfsHost && `obfs-host=${node.obfsHost}`
            ])
        case 'tuic':
            return appendParts(`${node.name} = tuic, ${node.server}, ${node.port}, token=${node.token || node.password}`, [
                node.alpn?.length && `alpn=${node.alpn[0]}`,
                node.sni && `sni=${node.sni}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true',
                options.udp && 'udp-relay=true'
            ])
        case 'anytls':
            return appendParts(`${node.name} = anytls, ${node.server}, ${node.port}, password=${node.password}`, [
                node.sni && `sni=${node.sni}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'http':
            return appendParts(`${node.name} = http, ${node.server}, ${node.port}`, [
                node.username && `username=${node.username}`,
                node.password && `password=${node.password}`,
                node.tls && 'tls=true',
                node.sni && `sni=${node.sni}`,
                (node.tls && options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'socks5':
            return appendParts(`${node.name} = socks5, ${node.server}, ${node.port}`, [
                node.username && `username=${node.username}`,
                node.password && `password=${node.password}`
            ])
        default:
            return ''
    }
}

function convertToQuantumultX(nodes, options) {
    return nodes.map(node => {
        switch (node.type) {
            case 'ss':
                return `shadowsocks=${node.server}:${node.port}, method=${node.method}, password=${node.password}, udp-relay=${options.udp}, tag=${node.name}`
            case 'vmess':
                return appendParts(`vmess=${node.server}:${node.port}, method=${node.cipher || 'auto'}, password=${node.uuid}, tag=${node.name}`, [
                    node.tls && 'tls=1',
                    node.sni && `tls-host=${node.sni}`,
                    node.ws && 'obfs=ws',
                    node.ws?.path && `obfs-uri=${node.ws.path}`,
                    node.ws?.headers?.Host && `obfs-host=${node.ws.headers.Host}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'vless':
                return appendParts(`vless=${node.server}:${node.port}, method=none, password=${node.uuid}, tag=${node.name}`, [
                    node.ws ? (node.tls ? 'obfs=wss' : 'obfs=ws') : (node.tls && 'obfs=over-tls'),
                    node.sni && `tls-host=${node.sni}`,
                    node.flow && `vless-flow=${node.flow}`,
                    node.reality?.publicKey && `reality-base64-pubkey=${node.reality.publicKey}`,
                    node.reality?.shortId && `reality-hex-shortid=${node.reality.shortId}`,
                    node.ws?.path && `obfs-uri=${node.ws.path}`,
                    node.ws?.headers?.Host && `obfs-host=${node.ws.headers.Host}`,
                    `udp-relay=${options.udp}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'trojan':
                return appendParts(`trojan=${node.server}:${node.port}, password=${node.password}, tag=${node.name}`, [
                    node.sni && `tls-host=${node.sni}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'anytls':
                return appendParts(`anytls=${node.server}:${node.port}, password=${node.password}, tag=${node.name}`, [
                    'over-tls=true',
                    node.sni && `tls-host=${node.sni}`,
                    `udp-relay=${options.udp}`,
                    (node.insecure || options.skipCert) && 'tls-verification=false'
                ])
            case 'http':
                return appendParts(`http=${node.server}:${node.port}, tag=${node.name}`, [
                    node.username && `username=${node.username}`,
                    node.password && `password=${node.password}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-host=${node.sni}`,
                    (node.tls && options.skipCert) && 'tls-verification=false'
                ])
            case 'socks5':
                return appendParts(`socks5=${node.server}:${node.port}, tag=${node.name}`, [
                    node.username && `username=${node.username}`,
                    node.password && `password=${node.password}`
                ])
            default:
                return ''
        }
    }).filter(Boolean).join('\n')
}

function convertToLoon(nodes, options) {
    return nodes.map(node => {
        switch (node.type) {
            case 'ss':
                return appendParts(`${node.name} = Shadowsocks,${node.server},${node.port},${node.method},"${node.password}"`, [
                    `udp=${options.udp}`
                ])
            case 'ssr':
                return appendParts(`${node.name} = ShadowsocksR,${node.server},${node.port},${node.method},"${node.password}"`, [
                    node.protocol && `protocol=${node.protocol}`,
                    node.protocolParam && `protocol-param=${node.protocolParam}`,
                    node.obfs && `obfs=${node.obfs}`,
                    node.obfsParam && `obfs-param=${node.obfsParam}`,
                    `udp=${options.udp}`
                ])
            case 'vmess':
                return appendParts(`${node.name} = vmess,${node.server},${node.port},auto,"${node.uuid}"`, [
                    node.ws && 'transport=ws',
                    node.ws?.path && `path=${node.ws.path}`,
                    node.ws?.headers?.Host && `host=${node.ws.headers.Host}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-name=${node.sni}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'vless':
                return appendParts(`${node.name} = VLESS,${node.server},${node.port},"${node.uuid}"`, [
                    node.ws && 'transport=ws',
                    node.ws?.path && `path=${node.ws.path}`,
                    node.ws?.headers?.Host && `host=${node.ws.headers.Host}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-name=${node.sni}`,
                    node.flow && `flow=${node.flow}`,
                    node.reality && 'reality=true',
                    node.reality?.publicKey && `public-key=${node.reality.publicKey}`,
                    node.reality?.shortId && `short-id=${node.reality.shortId}`,
                    node.reality?.fingerprint && `client-fingerprint=${node.reality.fingerprint}`,
                    `udp=${options.udp}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'trojan':
                return appendParts(`${node.name} = trojan,${node.server},${node.port},"${node.password}"`, [
                    node.sni && `sni=${node.sni}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'hysteria2':
                return appendParts(`${node.name} = Hysteria2,${node.server},${node.port},"${node.password}"`, [
                    node.sni && `sni=${node.sni}`,
                    node.obfsPassword && `salamander-password=${node.obfsPassword}`,
                    `udp=${options.udp}`,
                    (node.insecure || options.skipCert) && 'skip-cert-verify=true'
                ])
            case 'anytls':
                return appendParts(`${node.name} = AnyTLS,${node.server},${node.port},"${node.password}"`, [
                    node.sni && `sni=${node.sni}`,
                    `udp=${options.udp}`,
                    (node.insecure || options.skipCert) && 'skip-cert-verify=true'
                ])
            case 'http':
                return appendParts(`${node.name} = http,${node.server},${node.port}`, [
                    node.username && `username=${node.username}`,
                    node.password && `password=${node.password}`,
                    node.tls && 'over-tls=true',
                    node.sni && `sni=${node.sni}`
                ])
            case 'socks5':
                return appendParts(`${node.name} = socks5,${node.server},${node.port}`, [
                    node.username && `username=${node.username}`,
                    node.password && `password=${node.password}`
                ])
            default:
                return ''
        }
    }).filter(Boolean).join('\n')
}

function convertToBase64(nodes) {
    const links = nodes.map(toShareLink).filter(Boolean)
    return base64.encode(links.join('\n'))
}

function toShareLink(node) {
    switch (node.type) {
        case 'ss':
            return `ss://${base64.encode(`${node.method}:${node.password}`)}@${node.server}:${node.port}#${encodeURIComponent(node.name)}`
        case 'ssr': {
            const main = `${node.server}:${node.port}:${node.protocol}:${node.method}:${node.obfs}:${base64.encodeUrl(node.password)}`
            const params = new URLSearchParams()
            if (node.protocolParam) params.set('protoparam', base64.encodeUrl(node.protocolParam))
            if (node.obfsParam) params.set('obfsparam', base64.encodeUrl(node.obfsParam))
            params.set('remarks', base64.encodeUrl(node.name))
            return `ssr://${base64.encodeUrl(`${main}/?${params.toString()}`)}`
        }
        case 'vmess':
            return `vmess://${base64.encode(JSON.stringify({
                v: '2',
                ps: node.name,
                add: node.server,
                port: String(node.port),
                id: node.uuid,
                aid: String(node.alterId || 0),
                scy: node.cipher || 'auto',
                net: node.network || 'tcp',
                type: 'none',
                host: node.ws?.headers?.Host || '',
                path: node.ws?.path || node.grpc?.serviceName || '',
                tls: node.tls ? 'tls' : '',
                sni: node.sni || ''
            }))}`
        case 'vless': {
            const params = new URLSearchParams({ encryption: 'none', type: node.network || 'tcp' })
            if (node.security) params.set('security', node.security)
            else if (node.tls) params.set('security', 'tls')
            if (node.flow) params.set('flow', node.flow)
            if (node.sni) params.set('sni', node.sni)
            if (node.ws?.path) params.set('path', node.ws.path)
            if (node.ws?.headers?.Host) params.set('host', node.ws.headers.Host)
            if (node.grpc?.serviceName) params.set('serviceName', node.grpc.serviceName)
            if (node.reality) {
                params.set('security', 'reality')
                if (node.reality.publicKey) params.set('pbk', node.reality.publicKey)
                if (node.reality.shortId) params.set('sid', node.reality.shortId)
                params.set('fp', node.reality.fingerprint || 'chrome')
            }
            return `vless://${node.uuid}@${node.server}:${node.port}?${params.toString()}#${encodeURIComponent(node.name)}`
        }
        case 'trojan': {
            const params = new URLSearchParams()
            if (node.sni) params.set('sni', node.sni)
            if (node.alpn?.length) params.set('alpn', node.alpn.join(','))
            if (node.network === 'ws') params.set('type', 'ws')
            if (node.ws?.path) params.set('path', node.ws.path)
            if (node.ws?.headers?.Host) params.set('host', node.ws.headers.Host)
            return `trojan://${encodeURIComponent(node.password)}@${node.server}:${node.port}?${params.toString()}#${encodeURIComponent(node.name)}`
        }
        case 'hysteria':
            return `hysteria://${node.server}:${node.port}?${new URLSearchParams({
                auth: node.auth,
                upmbps: String(node.up),
                downmbps: String(node.down),
                alpn: node.alpn || 'h3',
                peer: node.sni || node.server,
                ...(node.obfs ? { obfs: node.obfs } : {}),
                ...(node.insecure ? { insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'hysteria2':
            return `hysteria2://${encodeURIComponent(node.password)}@${node.server}:${node.port}?${new URLSearchParams({
                sni: node.sni || node.server,
                ...(node.obfs ? { obfs: node.obfs, 'obfs-password': node.obfsPassword || '' } : {}),
                ...(node.insecure ? { insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'tuic':
            return `tuic://${node.uuid}:${encodeURIComponent(node.password)}@${node.server}:${node.port}?${new URLSearchParams({
                congestion_control: node.congestion || 'bbr',
                alpn: (node.alpn || ['h3']).join(','),
                sni: node.sni || node.server,
                udp_relay_mode: node.udpRelayMode || 'native',
                ...(node.insecure ? { allow_insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'snell':
            return `snell://${encodeURIComponent(node.psk)}@${node.server}:${node.port}?${new URLSearchParams({
                version: String(node.version || 3),
                ...(node.obfs ? { obfs: node.obfs } : {}),
                ...(node.obfsHost ? { 'obfs-host': node.obfsHost } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'anytls':
            return `anytls://${encodeURIComponent(node.password)}@${node.server}:${node.port}?${new URLSearchParams({
                sni: node.sni || node.server,
                ...(node.alpn?.length ? { alpn: node.alpn.join(',') } : {}),
                ...(node.fingerprint ? { fp: node.fingerprint } : {}),
                ...(node.insecure ? { insecure: '1' } : {}),
                ...(node.idleSessionCheckInterval ? { 'idle-session-check-interval': String(node.idleSessionCheckInterval) } : {}),
                ...(node.idleSessionTimeout ? { 'idle-session-timeout': String(node.idleSessionTimeout) } : {}),
                ...(node.minIdleSession !== undefined ? { 'min-idle-session': String(node.minIdleSession) } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'http':
            return `${node.tls ? 'https' : 'http'}://${authPrefix(node)}${node.server}:${node.port}#${encodeURIComponent(node.name)}`
        case 'socks5':
            return `socks5://${authPrefix(node)}${node.server}:${node.port}#${encodeURIComponent(node.name)}`
        default:
            return ''
    }
}

function convertToSingBox(nodes, options) {
    const outbounds = nodes.map(node => toSingBoxOutbound(node, options)).filter(Boolean)
    return JSON.stringify({
        log: { level: 'info' },
        outbounds: [
            { tag: 'proxy', type: 'selector', outbounds: outbounds.map(o => o.tag) },
            ...outbounds,
            { tag: 'direct', type: 'direct' }
        ]
    }, null, 2)
}

function toSingBoxOutbound(node, options) {
    const base = { tag: node.name, server: node.server, server_port: node.port }
    switch (node.type) {
        case 'ss':
            return { ...base, type: 'shadowsocks', method: node.method, password: node.password }
        case 'vmess':
            return withSingBoxTransport({
                ...base,
                type: 'vmess',
                uuid: node.uuid,
                alter_id: node.alterId || 0,
                security: node.cipher || 'auto',
                tls: node.tls ? tlsConfig(node.sni || node.server, options.skipCert) : undefined
            }, node)
        case 'vless':
            return withSingBoxTransport({
                ...base,
                type: 'vless',
                uuid: node.uuid,
                flow: node.flow || undefined,
                tls: node.tls ? {
                    ...tlsConfig(node.sni || node.server, options.skipCert, undefined, node.reality?.fingerprint),
                    reality: node.reality ? {
                        enabled: true,
                        public_key: node.reality.publicKey,
                        short_id: node.reality.shortId || undefined
                    } : undefined
                } : undefined
            }, node)
        case 'trojan':
            return withSingBoxTransport({
                ...base,
                type: 'trojan',
                password: node.password,
                tls: tlsConfig(node.sni || node.server, options.skipCert)
            }, node)
        case 'hysteria':
            return {
                ...base,
                type: 'hysteria',
                auth_str: node.auth,
                up_mbps: node.up,
                down_mbps: node.down,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn ? [node.alpn] : ['h3']),
                obfs: node.obfs || undefined
            }
        case 'hysteria2':
            return {
                ...base,
                type: 'hysteria2',
                password: node.password,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert),
                obfs: node.obfs ? { type: node.obfs, password: node.obfsPassword || '' } : undefined
            }
        case 'tuic':
            return {
                ...base,
                type: 'tuic',
                uuid: node.uuid,
                password: node.password,
                congestion_control: node.congestion || 'bbr',
                udp_relay_mode: node.udpRelayMode || 'native',
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn || ['h3'])
            }
        case 'anytls':
            return {
                ...base,
                type: 'anytls',
                password: node.password,
                idle_session_check_interval: node.idleSessionCheckInterval || undefined,
                idle_session_timeout: node.idleSessionTimeout || undefined,
                min_idle_session: node.minIdleSession ?? undefined,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn, node.fingerprint)
            }
        case 'http':
            return {
                ...base,
                type: 'http',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls ? tlsConfig(node.sni || node.server, options.skipCert) : undefined
            }
        case 'socks5':
            return {
                ...base,
                type: 'socks',
                version: '5',
                username: node.username || undefined,
                password: node.password || undefined
            }
        default:
            return null
    }
}

function withSingBoxTransport(outbound, node) {
    if (node.network === 'ws' && node.ws) {
        outbound.transport = {
            type: 'ws',
            path: node.ws.path || '/',
            headers: node.ws.headers || {}
        }
    }
    if (node.network === 'grpc' && node.grpc) {
        outbound.transport = {
            type: 'grpc',
            service_name: node.grpc.serviceName || ''
        }
    }
    return dropUndefined(outbound)
}

function tlsConfig(serverName, insecure, alpn, fingerprint) {
    return dropUndefined({
        enabled: true,
        server_name: serverName,
        insecure,
        alpn,
        utls: fingerprint ? { enabled: true, fingerprint } : undefined
    })
}

function appendParts(base, parts) {
    const extra = parts.filter(Boolean)
    return extra.length ? `${base}, ${extra.join(', ')}` : base
}

function authPrefix(node) {
    if (!node.username && !node.password) return ''
    const user = encodeURIComponent(node.username || '')
    const password = node.password ? `:${encodeURIComponent(node.password)}` : ''
    return `${user}${password}@`
}

function dropUndefined(value) {
    if (Array.isArray(value)) return value.map(dropUndefined)
    if (!value || typeof value !== 'object') return value
    return Object.fromEntries(
        Object.entries(value)
            .filter(([, item]) => item !== undefined && item !== null)
            .map(([key, item]) => [key, dropUndefined(item)])
    )
}
