import yaml from 'js-yaml'
import { applyRulePreset } from './rules.js'
import { base64 } from './parsers.js'
import {
    BASE64_TARGETS,
    SING_BOX_TARGETS,
    YAML_TARGETS,
    normalizeTarget,
    supportedNodeTypesForTarget
} from './targets.js'

export function convertToTarget(nodes, target, options = {}) {
    const normalized = normalizeTarget(target)
    const compatibleNodes = prepareNodes(nodes, normalized)
    if (!compatibleNodes.length) return ''
    const safeOptions = {
        udp: options.udp !== false,
        skipCert: options.skipCert === true,
        rulePreset: options.rulePreset || ''
    }

    if (YAML_TARGETS.has(normalized)) return convertToClash(compatibleNodes, safeOptions, normalized)
    if (normalized === 'surge' || normalized === 'surfboard') return convertToSurge(compatibleNodes, safeOptions, normalized)
    if (normalized === 'quantumultx') return convertToQuantumultX(compatibleNodes, safeOptions)
    if (normalized === 'loon') return convertToLoon(compatibleNodes, safeOptions)
    if (BASE64_TARGETS.has(normalized)) return convertToBase64(compatibleNodes)
    if (SING_BOX_TARGETS.has(normalized)) return convertToSingBox(compatibleNodes, safeOptions)
    return ''
}

function convertToClash(nodes, options, target) {
    const proxies = nodes.map(node => toClashProxy(node, options, target)).filter(Boolean)
    if (!proxies.length) return ''
    const names = proxies.map(proxy => proxy.name)
    const { proxyGroups, rules } = options.rulePreset
        ? applyRulePreset(names, options.rulePreset)
        : applyRulePreset(names, 'basic')

    return [
        '# Generated by 订阅转换',
        `# Nodes: ${proxies.length}`,
        `# Target: ${target}`,
        `# Generated: ${new Date().toISOString()}`,
        '',
        yaml.dump({
            proxies,
            'proxy-groups': proxyGroups,
            rules
        }, {
            lineWidth: -1,
            noRefs: true,
            sortKeys: false
        })
    ].join('\n')
}

function toClashProxy(node, options, target) {
    const extended = target !== 'clash'
    const base = {
        name: node.name,
        server: node.server,
        port: node.port,
        udp: options.udp
    }

    switch (node.type) {
        case 'ss':
            return dropUndefined({
                ...base,
                type: 'ss',
                cipher: node.method,
                password: node.password,
                plugin: clashPluginName(node.plugin),
                'plugin-opts': normalizePluginOptions(node.pluginOpts)
            })
        case 'ssr':
            return {
                ...base,
                type: 'ssr',
                cipher: node.method,
                password: node.password,
                protocol: node.protocol,
                'protocol-param': node.protocolParam || '',
                obfs: node.obfs,
                'obfs-param': node.obfsParam || ''
            }
        case 'vmess':
            return withTransport({
                ...base,
                type: 'vmess',
                uuid: node.uuid,
                alterId: node.alterId || 0,
                cipher: node.cipher || 'auto',
                tls: node.tls || undefined,
                servername: node.tls ? node.sni : undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined,
                network: node.network !== 'tcp' ? node.network : undefined
            }, node)
        case 'vless':
            if (!extended) return null
            return withTransport({
                ...base,
                type: 'vless',
                uuid: node.uuid,
                flow: node.flow || undefined,
                tls: node.tls || undefined,
                servername: node.sni || undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined,
                network: node.network !== 'tcp' ? node.network : undefined,
                'reality-opts': node.reality ? {
                    'public-key': node.reality.publicKey,
                    'short-id': node.reality.shortId || undefined
                } : undefined,
                'client-fingerprint': node.reality?.fingerprint || undefined
            }, node)
        case 'trojan':
            return withTransport({
                ...base,
                type: 'trojan',
                password: node.password,
                sni: node.sni || undefined,
                alpn: node.alpn?.length ? node.alpn : undefined,
                'skip-cert-verify': options.skipCert
            }, node)
        case 'hysteria':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'hysteria',
                ...(target === 'stash'
                    ? {
                        'auth-str': node.auth,
                        'up-speed': node.up,
                        'down-speed': node.down
                    }
                    : {
                        auth_str: node.auth,
                        up: node.up,
                        down: node.down
                    }),
                alpn: [node.alpn || 'h3'],
                obfs: node.obfs || undefined,
                sni: node.sni || undefined,
                'skip-cert-verify': node.insecure || options.skipCert
            })
        case 'hysteria2':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'hysteria2',
                ...(target === 'stash' ? { auth: node.password } : { password: node.password }),
                sni: node.sni || undefined,
                obfs: node.obfs || undefined,
                'obfs-password': node.obfs ? node.obfsPassword || '' : undefined,
                'skip-cert-verify': node.insecure || options.skipCert
            })
        case 'tuic':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'tuic',
                version: target === 'stash' ? (node.token && !node.password ? 4 : 5) : undefined,
                uuid: node.password ? node.uuid : undefined,
                password: node.password || undefined,
                token: node.token && !node.password ? node.token : undefined,
                alpn: node.alpn || ['h3'],
                'congestion-controller': node.congestion || 'bbr',
                sni: node.sni || undefined,
                'skip-cert-verify': node.insecure || options.skipCert,
                'udp-relay-mode': node.udpRelayMode || 'native',
                'reduce-rtt': true
            })
        case 'anytls':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'anytls',
                password: node.password,
                sni: node.sni || undefined,
                alpn: node.alpn?.length ? node.alpn : undefined,
                'skip-cert-verify': node.insecure || options.skipCert,
                'client-fingerprint': node.fingerprint || undefined,
                'idle-session-check-interval': node.idleSessionCheckInterval || undefined,
                'idle-session-timeout': node.idleSessionTimeout || undefined,
                'min-idle-session': node.minIdleSession ?? undefined
            })
        case 'snell':
            if (!extended) return null
            return dropUndefined({
                ...base,
                type: 'snell',
                psk: node.psk,
                version: node.version || 3,
                obfs: node.obfs || undefined,
                'obfs-opts': node.obfs ? { mode: node.obfs, host: node.obfsHost || undefined } : undefined
            })
        case 'http':
            return dropUndefined({
                ...base,
                type: 'http',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls || undefined,
                sni: node.sni || undefined,
                'skip-cert-verify': node.tls ? options.skipCert : undefined
            })
        case 'socks5':
            return dropUndefined({
                ...base,
                type: 'socks5',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls || undefined
            })
        default:
            return null
    }
}

function withTransport(proxy, node) {
    if (node.network === 'ws' && node.ws) {
        proxy.network = 'ws'
        proxy['ws-opts'] = {
            path: node.ws.path || '/',
            headers: node.ws.headers || {}
        }
    }
    if (node.network === 'grpc' && node.grpc) {
        proxy.network = 'grpc'
        proxy['grpc-opts'] = {
            'grpc-service-name': node.grpc.serviceName || ''
        }
    }
    return dropUndefined(proxy)
}

function convertToSurge(nodes, options, target) {
    const proxies = nodes
        .map(node => ({ node, line: toSurgeLine(node, options, target) }))
        .filter(item => item.line)
    const lines = ['[Proxy]']
    for (const proxy of proxies) lines.push(proxy.line)
    if (!proxies.length) return ''

    lines.push('', '[Proxy Group]', `PROXY = select, ${proxies.map(item => inlineName(item.node.name)).join(', ')}`)
    lines.push('', '[Rule]', 'GEOIP,CN,DIRECT', 'FINAL,PROXY')
    return lines.join('\n')
}

function toSurgeLine(node, options, target) {
    const name = inlineName(node.name)
    const server = formatHost(node.server)
    switch (node.type) {
        case 'ss':
            return appendParts(`${name} = ss, ${server}, ${node.port}, encrypt-method=${node.method}, password=${confValue(node.password)}`, [
                `udp-relay=${options.udp}`,
                shadowsocksObfs(node.plugin, node.pluginOpts, 'mode'),
                shadowsocksObfs(node.plugin, node.pluginOpts, 'host')
            ])
        case 'vmess':
            return appendParts(`${name} = vmess, ${server}, ${node.port}, username=${confValue(node.uuid)}`, [
                'vmess-aead=true',
                node.tls && 'tls=true',
                node.sni && `sni=${confValue(node.sni)}`,
                node.ws && 'ws=true',
                node.ws?.path && `ws-path=${confValue(node.ws.path)}`,
                node.ws?.headers?.Host && `ws-headers=Host:${confValue(node.ws.headers.Host)}`,
                options.skipCert && 'skip-cert-verify=true'
            ])
        case 'trojan':
            return appendParts(`${name} = trojan, ${server}, ${node.port}, password=${confValue(node.password)}`, [
                node.sni && `sni=${confValue(node.sni)}`,
                options.skipCert && 'skip-cert-verify=true'
            ])
        case 'hysteria2':
            return appendParts(`${name} = hysteria2, ${server}, ${node.port}, password=${confValue(node.password)}`, [
                node.sni && `sni=${confValue(node.sni)}`,
                node.obfsPassword && `salamander-password=${confValue(node.obfsPassword)}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'snell':
            return appendParts(`${name} = snell, ${server}, ${node.port}, psk=${confValue(node.psk)}, version=${node.version || 3}`, [
                node.obfs && `obfs=${node.obfs}`,
                node.obfsHost && `obfs-host=${confValue(node.obfsHost)}`,
                `udp-relay=${options.udp}`
            ])
        case 'tuic':
            if (!node.token) return ''
            return appendParts(`${name} = tuic, ${server}, ${node.port}, token=${confValue(node.token)}`, [
                node.alpn?.length && `alpn=${node.alpn[0]}`,
                node.sni && `sni=${confValue(node.sni)}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true',
                options.udp && 'udp-relay=true'
            ])
        case 'anytls':
            return appendParts(`${name} = anytls, ${server}, ${node.port}, password=${confValue(node.password)}`, [
                node.sni && `sni=${confValue(node.sni)}`,
                (node.insecure || options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'http':
            return appendParts(`${name} = ${node.tls ? 'https' : 'http'}, ${server}, ${node.port}${positionalAuth(node)}`, [
                node.sni && `sni=${confValue(node.sni)}`,
                (node.tls && options.skipCert) && 'skip-cert-verify=true'
            ])
        case 'socks5':
            return appendParts(`${name} = ${node.tls ? 'socks5-tls' : 'socks5'}, ${server}, ${node.port}${positionalAuth(node)}`, [
                `udp-relay=${options.udp}`,
                node.tls && node.sni && `sni=${confValue(node.sni)}`,
                (node.tls && options.skipCert) && 'skip-cert-verify=true'
            ])
        default:
            return ''
    }
}

function convertToQuantumultX(nodes, options) {
    return nodes.map(node => {
        const name = inlineName(node.name)
        const server = formatHost(node.server)
        switch (node.type) {
            case 'ss':
                return appendParts(`shadowsocks=${server}:${node.port}, method=${node.method}, password=${confValue(node.password)}`, [
                    shadowsocksObfs(node.plugin, node.pluginOpts, 'mode'),
                    shadowsocksObfs(node.plugin, node.pluginOpts, 'host'),
                    `udp-relay=${options.udp}`,
                    `tag=${name}`
                ])
            case 'vmess':
                return appendParts(`vmess=${server}:${node.port}, method=${node.cipher || 'auto'}, password=${confValue(node.uuid)}, tag=${name}`, [
                    node.tls && 'tls=1',
                    node.sni && `tls-host=${node.sni}`,
                    node.ws && 'obfs=ws',
                    node.ws?.path && `obfs-uri=${node.ws.path}`,
                    node.ws?.headers?.Host && `obfs-host=${node.ws.headers.Host}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'vless':
                return appendParts(`vless=${server}:${node.port}, method=none, password=${confValue(node.uuid)}, tag=${name}`, [
                    node.ws ? (node.tls ? 'obfs=wss' : 'obfs=ws') : (node.tls && 'obfs=over-tls'),
                    node.sni && `tls-host=${node.sni}`,
                    node.flow && `vless-flow=${node.flow}`,
                    node.reality?.publicKey && `reality-base64-pubkey=${node.reality.publicKey}`,
                    node.reality?.shortId && `reality-hex-shortid=${node.reality.shortId}`,
                    node.ws?.path && `obfs-uri=${node.ws.path}`,
                    node.ws?.headers?.Host && `obfs-host=${node.ws.headers.Host}`,
                    `udp-relay=${options.udp}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'trojan':
                return appendParts(`trojan=${server}:${node.port}, password=${confValue(node.password)}, tag=${name}`, [
                    node.sni && `tls-host=${node.sni}`,
                    options.skipCert && 'tls-verification=false'
                ])
            case 'anytls':
                return appendParts(`anytls=${server}:${node.port}, password=${confValue(node.password)}, tag=${name}`, [
                    'over-tls=true',
                    node.sni && `tls-host=${node.sni}`,
                    `udp-relay=${options.udp}`,
                    (node.insecure || options.skipCert) && 'tls-verification=false'
                ])
            case 'http':
                return appendParts(`http=${server}:${node.port}, tag=${name}`, [
                    node.username && `username=${confValue(node.username)}`,
                    node.password && `password=${confValue(node.password)}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-host=${node.sni}`,
                    (node.tls && options.skipCert) && 'tls-verification=false'
                ])
            case 'socks5':
                return appendParts(`socks5=${server}:${node.port}, tag=${name}`, [
                    node.username && `username=${confValue(node.username)}`,
                    node.password && `password=${confValue(node.password)}`
                ])
            default:
                return ''
        }
    }).filter(Boolean).join('\n')
}

function convertToLoon(nodes, options) {
    return nodes.map(node => {
        const name = inlineName(node.name)
        const server = formatHost(node.server)
        switch (node.type) {
            case 'ss':
                return appendParts(`${name} = Shadowsocks,${server},${node.port},${node.method},${quotedValue(node.password)}`, [
                    loonShadowsocksObfs(node.plugin, node.pluginOpts, 'mode'),
                    loonShadowsocksObfs(node.plugin, node.pluginOpts, 'host'),
                    `udp=${options.udp}`
                ])
            case 'ssr':
                return appendParts(`${name} = ShadowsocksR,${server},${node.port},${node.method},${quotedValue(node.password)}`, [
                    node.protocol && `protocol=${node.protocol}`,
                    node.protocolParam && `protocol-param=${node.protocolParam}`,
                    node.obfs && `obfs=${node.obfs}`,
                    node.obfsParam && `obfs-param=${node.obfsParam}`,
                    `udp=${options.udp}`
                ])
            case 'vmess':
                return appendParts(`${name} = vmess,${server},${node.port},auto,${quotedValue(node.uuid)}`, [
                    node.ws && 'transport=ws',
                    node.ws?.path && `path=${node.ws.path}`,
                    node.ws?.headers?.Host && `host=${node.ws.headers.Host}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-name=${node.sni}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'vless':
                return appendParts(`${name} = VLESS,${server},${node.port},${quotedValue(node.uuid)}`, [
                    node.ws && 'transport=ws',
                    node.ws?.path && `path=${node.ws.path}`,
                    node.ws?.headers?.Host && `host=${node.ws.headers.Host}`,
                    node.tls && 'over-tls=true',
                    node.sni && `tls-name=${node.sni}`,
                    node.flow && `flow=${node.flow}`,
                    node.reality?.publicKey && `public-key=${node.reality.publicKey}`,
                    node.reality?.shortId && `short-id=${node.reality.shortId}`,
                    node.reality?.fingerprint && `client-fingerprint=${node.reality.fingerprint}`,
                    `udp=${options.udp}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'trojan':
                return appendParts(`${name} = trojan,${server},${node.port},${quotedValue(node.password)}`, [
                    node.sni && `sni=${node.sni}`,
                    options.skipCert && 'skip-cert-verify=true'
                ])
            case 'hysteria2':
                return appendParts(`${name} = Hysteria2,${server},${node.port},${quotedValue(node.password)}`, [
                    node.sni && `sni=${node.sni}`,
                    node.obfsPassword && `salamander-password=${node.obfsPassword}`,
                    `udp=${options.udp}`,
                    (node.insecure || options.skipCert) && 'skip-cert-verify=true'
                ])
            case 'anytls':
                return appendParts(`${name} = AnyTLS,${server},${node.port},${quotedValue(node.password)}`, [
                    node.sni && `sni=${node.sni}`,
                    `udp=${options.udp}`,
                    (node.insecure || options.skipCert) && 'skip-cert-verify=true'
                ])
            case 'http':
                return appendParts(`${name} = http,${server},${node.port}`, [
                    node.username && `username=${confValue(node.username)}`,
                    node.password && `password=${confValue(node.password)}`,
                    node.tls && 'over-tls=true',
                    node.sni && `sni=${node.sni}`
                ])
            case 'socks5':
                return appendParts(`${name} = socks5,${server},${node.port}`, [
                    node.username && `username=${confValue(node.username)}`,
                    node.password && `password=${confValue(node.password)}`
                ])
            default:
                return ''
        }
    }).filter(Boolean).join('\n')
}

function convertToBase64(nodes) {
    const links = nodes.map(toShareLink).filter(Boolean)
    return base64.encode(links.join('\n'))
}

function toShareLink(node) {
    const host = formatHost(node.server)
    switch (node.type) {
        case 'ss': {
            const plugin = serializePlugin(node.plugin, node.pluginOpts)
            const query = plugin ? `/?plugin=${encodeURIComponent(plugin)}` : ''
            return `ss://${base64.encode(`${node.method}:${node.password}`)}@${host}:${node.port}${query}#${encodeURIComponent(node.name)}`
        }
        case 'ssr': {
            const main = `${host}:${node.port}:${node.protocol}:${node.method}:${node.obfs}:${base64.encodeUrl(node.password)}`
            const params = new URLSearchParams()
            if (node.protocolParam) params.set('protoparam', base64.encodeUrl(node.protocolParam))
            if (node.obfsParam) params.set('obfsparam', base64.encodeUrl(node.obfsParam))
            params.set('remarks', base64.encodeUrl(node.name))
            return `ssr://${base64.encodeUrl(`${main}/?${params.toString()}`)}`
        }
        case 'vmess':
            return `vmess://${base64.encode(JSON.stringify({
                v: '2',
                ps: node.name,
                add: node.server,
                port: String(node.port),
                id: node.uuid,
                aid: String(node.alterId || 0),
                scy: node.cipher || 'auto',
                net: node.network || 'tcp',
                type: 'none',
                host: node.ws?.headers?.Host || '',
                path: node.ws?.path || node.grpc?.serviceName || '',
                tls: node.tls ? 'tls' : '',
                sni: node.sni || ''
            }))}`
        case 'vless': {
            const params = new URLSearchParams({ encryption: 'none', type: node.network || 'tcp' })
            if (node.security) params.set('security', node.security)
            else if (node.tls) params.set('security', 'tls')
            if (node.flow) params.set('flow', node.flow)
            if (node.sni) params.set('sni', node.sni)
            if (node.ws?.path) params.set('path', node.ws.path)
            if (node.ws?.headers?.Host) params.set('host', node.ws.headers.Host)
            if (node.grpc?.serviceName) params.set('serviceName', node.grpc.serviceName)
            if (node.reality) {
                params.set('security', 'reality')
                if (node.reality.publicKey) params.set('pbk', node.reality.publicKey)
                if (node.reality.shortId) params.set('sid', node.reality.shortId)
                params.set('fp', node.reality.fingerprint || 'chrome')
            }
            return `vless://${encodeURIComponent(node.uuid)}@${host}:${node.port}?${params.toString()}#${encodeURIComponent(node.name)}`
        }
        case 'trojan': {
            const params = new URLSearchParams()
            if (node.sni) params.set('sni', node.sni)
            if (node.alpn?.length) params.set('alpn', node.alpn.join(','))
            if (node.network === 'ws') params.set('type', 'ws')
            if (node.ws?.path) params.set('path', node.ws.path)
            if (node.ws?.headers?.Host) params.set('host', node.ws.headers.Host)
            return `trojan://${encodeURIComponent(node.password)}@${host}:${node.port}?${params.toString()}#${encodeURIComponent(node.name)}`
        }
        case 'hysteria':
            return `hysteria://${host}:${node.port}?${new URLSearchParams({
                auth: node.auth,
                upmbps: String(node.up),
                downmbps: String(node.down),
                alpn: node.alpn || 'h3',
                peer: node.sni || node.server,
                ...(node.obfs ? { obfs: node.obfs } : {}),
                ...(node.insecure ? { insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'hysteria2':
            return `hysteria2://${encodeURIComponent(node.password)}@${host}:${node.port}?${new URLSearchParams({
                sni: node.sni || node.server,
                ...(node.obfs ? { obfs: node.obfs, 'obfs-password': node.obfsPassword || '' } : {}),
                ...(node.insecure ? { insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'tuic':
            return `tuic://${node.password
                ? `${encodeURIComponent(node.uuid)}:${encodeURIComponent(node.password)}`
                : encodeURIComponent(node.token)}@${host}:${node.port}?${new URLSearchParams({
                congestion_control: node.congestion || 'bbr',
                alpn: (node.alpn || ['h3']).join(','),
                sni: node.sni || node.server,
                udp_relay_mode: node.udpRelayMode || 'native',
                ...(node.insecure ? { allow_insecure: '1' } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'snell':
            return `snell://${encodeURIComponent(node.psk)}@${host}:${node.port}?${new URLSearchParams({
                version: String(node.version || 3),
                ...(node.obfs ? { obfs: node.obfs } : {}),
                ...(node.obfsHost ? { 'obfs-host': node.obfsHost } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'anytls':
            return `anytls://${encodeURIComponent(node.password)}@${host}:${node.port}?${new URLSearchParams({
                sni: node.sni || node.server,
                ...(node.alpn?.length ? { alpn: node.alpn.join(',') } : {}),
                ...(node.fingerprint ? { fp: node.fingerprint } : {}),
                ...(node.insecure ? { insecure: '1' } : {}),
                ...(node.idleSessionCheckInterval ? { 'idle-session-check-interval': String(node.idleSessionCheckInterval) } : {}),
                ...(node.idleSessionTimeout ? { 'idle-session-timeout': String(node.idleSessionTimeout) } : {}),
                ...(node.minIdleSession !== undefined ? { 'min-idle-session': String(node.minIdleSession) } : {})
            }).toString()}#${encodeURIComponent(node.name)}`
        case 'http':
            return `${node.tls ? 'https' : 'http'}://${authPrefix(node)}${host}:${node.port}#${encodeURIComponent(node.name)}`
        case 'socks5':
            return `socks5://${authPrefix(node)}${host}:${node.port}#${encodeURIComponent(node.name)}`
        default:
            return ''
    }
}

function convertToSingBox(nodes, options) {
    const outbounds = nodes.map(node => toSingBoxOutbound(node, options)).filter(Boolean)
    if (!outbounds.length) return ''
    return JSON.stringify({
        log: { level: 'info' },
        outbounds: [
            {
                tag: 'proxy',
                type: 'selector',
                outbounds: outbounds.map(outbound => outbound.tag),
                default: outbounds[0].tag
            },
            ...outbounds,
            { tag: 'direct', type: 'direct' }
        ],
        route: { final: 'proxy' }
    }, null, 2)
}

function toSingBoxOutbound(node, options) {
    const base = { tag: node.name, server: node.server, server_port: node.port }
    switch (node.type) {
        case 'ss':
            return dropUndefined({
                ...base,
                type: 'shadowsocks',
                method: node.method,
                password: node.password,
                plugin: singBoxPluginName(node.plugin),
                plugin_opts: serializePluginOptions(node.pluginOpts, node.plugin)
            })
        case 'vmess':
            return withSingBoxTransport({
                ...base,
                type: 'vmess',
                uuid: node.uuid,
                alter_id: node.alterId || 0,
                security: node.cipher || 'auto',
                tls: node.tls ? tlsConfig(node.sni || node.server, options.skipCert) : undefined
            }, node)
        case 'vless':
            return withSingBoxTransport({
                ...base,
                type: 'vless',
                uuid: node.uuid,
                flow: node.flow || undefined,
                tls: node.tls ? {
                    ...tlsConfig(node.sni || node.server, options.skipCert, undefined, node.reality?.fingerprint),
                    reality: node.reality ? {
                        enabled: true,
                        public_key: node.reality.publicKey,
                        short_id: node.reality.shortId || undefined
                    } : undefined
                } : undefined
            }, node)
        case 'trojan':
            return withSingBoxTransport({
                ...base,
                type: 'trojan',
                password: node.password,
                tls: tlsConfig(node.sni || node.server, options.skipCert)
            }, node)
        case 'hysteria':
            return {
                ...base,
                type: 'hysteria',
                auth_str: node.auth,
                up_mbps: node.up,
                down_mbps: node.down,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn ? [node.alpn] : ['h3']),
                obfs: node.obfs || undefined
            }
        case 'hysteria2':
            return {
                ...base,
                type: 'hysteria2',
                password: node.password,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert),
                obfs: node.obfs ? { type: node.obfs, password: node.obfsPassword || '' } : undefined
            }
        case 'tuic':
            return {
                ...base,
                type: 'tuic',
                uuid: node.uuid,
                password: node.password,
                congestion_control: node.congestion || 'bbr',
                udp_relay_mode: node.udpRelayMode || 'native',
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn || ['h3'])
            }
        case 'anytls':
            return {
                ...base,
                type: 'anytls',
                password: node.password,
                idle_session_check_interval: node.idleSessionCheckInterval || undefined,
                idle_session_timeout: node.idleSessionTimeout || undefined,
                min_idle_session: node.minIdleSession ?? undefined,
                tls: tlsConfig(node.sni || node.server, node.insecure || options.skipCert, node.alpn, node.fingerprint)
            }
        case 'http':
            return {
                ...base,
                type: 'http',
                username: node.username || undefined,
                password: node.password || undefined,
                tls: node.tls ? tlsConfig(node.sni || node.server, options.skipCert) : undefined
            }
        case 'socks5':
            return {
                ...base,
                type: 'socks',
                version: '5',
                username: node.username || undefined,
                password: node.password || undefined
            }
        default:
            return null
    }
}

function withSingBoxTransport(outbound, node) {
    if (node.network === 'ws' && node.ws) {
        outbound.transport = {
            type: 'ws',
            path: node.ws.path || '/',
            headers: node.ws.headers || {}
        }
    }
    if (node.network === 'grpc' && node.grpc) {
        outbound.transport = {
            type: 'grpc',
            service_name: node.grpc.serviceName || ''
        }
    }
    return dropUndefined(outbound)
}

function tlsConfig(serverName, insecure, alpn, fingerprint) {
    return dropUndefined({
        enabled: true,
        server_name: serverName,
        insecure,
        alpn,
        utls: fingerprint ? { enabled: true, fingerprint } : undefined
    })
}

function appendParts(base, parts) {
    const extra = parts.filter(Boolean)
    return extra.length ? `${base}, ${extra.join(', ')}` : base
}

function authPrefix(node) {
    if (!node.username && !node.password) return ''
    const user = encodeURIComponent(node.username || '')
    const password = node.password ? `:${encodeURIComponent(node.password)}` : ''
    return `${user}${password}@`
}

function prepareNodes(nodes, target) {
    const allowedTypes = supportedNodeTypesForTarget(target)
    const usedNames = new Set(['direct', 'reject', 'proxy'])

    return (Array.isArray(nodes) ? nodes : [])
        .filter(node => allowedTypes.has(node.type))
        .filter(node => !(SING_BOX_TARGETS.has(target) && node.type === 'tuic' && !node.password))
        .filter(node => !(target === 'surge' && node.type === 'tuic' && !node.token))
        .map((node, index) => {
            const baseName = String(node.name || `${String(node.type || 'proxy').toUpperCase()} Node ${index + 1}`)
                .replace(/[\u0000-\u001f\u007f]/g, ' ')
                .replace(/\s+/g, ' ')
                .trim() || `Proxy Node ${index + 1}`
            let name = baseName
            let suffix = 2
            while (usedNames.has(name.toLocaleLowerCase())) {
                name = `${baseName} #${suffix++}`
            }
            usedNames.add(name.toLocaleLowerCase())
            return { ...node, name }
        })
}

function inlineName(value) {
    return String(value || 'Proxy')
        .replace(/[\r\n,=]/g, '_')
        .trim() || 'Proxy'
}

function formatHost(value) {
    const host = String(value || '').replace(/^\[|\]$/g, '')
    return host.includes(':') ? `[${host}]` : host
}

function confValue(value) {
    const text = String(value ?? '')
    return /[\s,",]/.test(text) ? quotedValue(text) : text
}

function quotedValue(value) {
    return JSON.stringify(String(value ?? ''))
}

function positionalAuth(node) {
    if (!node.username && !node.password) return ''
    return `, ${confValue(node.username || '')}, ${confValue(node.password || '')}`
}

function normalizePluginOptions(value) {
    if (!value) return undefined
    if (typeof value === 'object') return value
    const entries = String(value)
        .split(';')
        .map(part => part.split('=', 2))
        .filter(([key]) => key)
    return entries.length ? Object.fromEntries(entries) : undefined
}

function serializePluginOptions(value, plugin) {
    if (!value) return ''
    if (typeof value === 'string') return value
    return Object.entries(value)
        .filter(([, item]) => item !== false && item !== undefined && item !== null && item !== '')
        .map(([key, item]) => {
            const optionKey = ['obfs', 'obfs-local'].includes(plugin)
                ? (key === 'mode' ? 'obfs' : (key === 'host' ? 'obfs-host' : key))
                : key
            return item === true ? optionKey : `${optionKey}=${item}`
        })
        .join(';')
}

function serializePlugin(plugin, options) {
    if (!plugin) return ''
    const name = singBoxPluginName(plugin)
    const serialized = serializePluginOptions(options, plugin)
    return serialized ? `${name};${serialized}` : name
}

function clashPluginName(plugin) {
    if (!plugin) return undefined
    return plugin === 'obfs-local' ? 'obfs' : plugin
}

function singBoxPluginName(plugin) {
    if (!plugin) return undefined
    return plugin === 'obfs' ? 'obfs-local' : plugin
}

function shadowsocksObfs(plugin, options, field) {
    if (!['obfs', 'obfs-local'].includes(plugin)) return ''
    const values = normalizePluginOptions(options) || {}
    if (field === 'mode' && values.mode) return `obfs=${values.mode}`
    if (field === 'host' && values.host) return `obfs-host=${confValue(values.host)}`
    return ''
}

function loonShadowsocksObfs(plugin, options, field) {
    if (!['obfs', 'obfs-local'].includes(plugin)) return ''
    const values = normalizePluginOptions(options) || {}
    if (field === 'mode' && values.mode) return `obfs-name=${values.mode}`
    if (field === 'host' && values.host) return `obfs-host=${confValue(values.host)}`
    return ''
}

function dropUndefined(value) {
    if (Array.isArray(value)) return value.map(dropUndefined)
    if (!value || typeof value !== 'object') return value
    return Object.fromEntries(
        Object.entries(value)
            .filter(([, item]) => item !== undefined && item !== null)
            .map(([key, item]) => [key, dropUndefined(item)])
    )
}
